### ISSUE TITLE
can't select resourcepacks file in macOS

### ISSUE THREAD

**Issue by zxcdevlop** [supsm/MCPPPP#16]
I try to click browse to select my resourcepacks folder, but nothing happens after selecting it. No resource packs show up on the right side after that. pls fix

**Comment by supsm** [comment]
Does the "Edit Paths" window appear? If so, did you click on the Add button and it opened a finder window? If all of this is true, is the resourcepacks box empty?
<img width="248" alt="image" src="https://user-images.githubusercontent.com/60897356/145145369-2d9bae31-f044-47cd-bd06-baf04b95a837.png">

**Comment by zxcdevlop** [comment]
all that is true, and the resourcepacks folder isn't empty

**Comment by supsm** [comment]
Thanks for reporting, someone else could reproduce the issue (I don’t have a Mac). I will try to fix the issue, but it could take a few days

**Comment by MrGcGamer** [comment]
I can confirm, this behaviour is indeed the case.

**Comment by supsm** [comment]
I released [0.5.7](https://github.com/supsm/MCPPPP/releases/tag/0.5.7), which should hopefully fix the issue. Can you try and make sure the issue is resolved?

**Comment by MrGcGamer** [comment]
Works now! (Didn't try converting, as I used the mod in the mean time, but the resourcepacks now load properly into the view)

**Comment by zxcdevlop** [comment]
works for me as well! thanks a lot!
