### ISSUE TITLE
Feature Request: cache the changed resources

### ISSUE THREAD

**Issue by Madis0** [supsm/MCPPPP#18]
**Is your feature request related to a problem? Please describe.**
You mentioned somewhere that the mod currently rebuilds the relevant resource packs on every startup, resulting in slower startup and higher resource usage.

**Describe the solution you'd like**
Based on a hash of currently activated resource packs, create the converted pack only once (after the user has changed their resource packs) and use it on every startup.

**Describe alternatives you've considered**
N/A

**Additional context**
This would only slow down the resource pack switching process itself

**Comment by supsm** [comment]
It doesn't reconvert the resourcepacks every time, instead it unzips it every time to check for files to convert. This process will be a lot faster and is already implemented, the only thing left now is to fix linker errors.......  
That is still a good idea though, as currently there is no way of knowing if the user changed any resourcepacks. I'm not sure if it's possible to convert a pack when reloading resources, as I'd either have to force the conversion to happen before any of the other mods access resources, or trigger another resource reload after the first conversion.

**Comment by i-like-trains72** [comment]
Well, MCPP++ does convert on the fly, so maybe look into their solution? (granted MCPP++ is ded)

**Comment by supsm** [comment]
Should be implemented in c990d08a92527edfce6a58adfb167f7d54b3b6d7
