### ISSUE TITLE
Textures based on named mobs don't transfer over

### ISSUE THREAD

**Issue by Garfieldwxg55** [supsm/MCPPPP#2]
In Optifine, mobs can be given custom textures based on what they are named, and this is able to be replicated in Varied Mob Textures with the name selector. However, this is not converted over when you convert the resource pack with the converter.

**Comment by supsm** [comment]
This is actually intentional. Using the name selector will cause the game to crash. I've opened a [pull request](https://github.com/Digifox03/variedMobs/pull/15) on vmt a while ago, but it's been suspended so I'm not sure when it'll get merged (hopefully summer)

**Comment by Garfieldwxg55** [comment]
Oh thanks, hopefully if it gets merged I'll be able to port my resource pack over then!

**Comment by supsm** [comment]
The changes actually are already there, just commented out. If you want, tell me your os and I'll build it for you

**Comment by Garfieldwxg55** [comment]
Oh I use Windows 10 Home

**Comment by supsm** [comment]
Try this, tell me if anything breaks. If you want to send your resource pack to someone else, they'll have to use my modified mod
[vmt.zip](https://github.com/supsm/MCPPPP/files/6593472/vmt.zip)
(I have to zip it because github won't let me upload `.exe` or `.jar`)

**Comment by supsm** [comment]
This will be fixed in 1.17 update of vmt (soon :)

**Comment by Garfieldwxg55** [comment]
Hi, I just recently tried using the conversion tool, and it seems to have not converted the resource pack properly. The log shows that  there are no files in the assets file, and skipped over the optifine folder (which is where all my custom textures are located). Is this a known issue? Many thanks

**Comment by supsm** [comment]
I'll look into it tomorrow

**Comment by Garfieldwxg55** [comment]
Thanks

**Comment by supsm** [comment]
Would you mind uploading the resource pack?

**Comment by supsm** [comment]
Nevermind, I think I spotted the issue
