### ISSUE TITLE
Resource pack failed to load

### ISSUE THREAD

**Issue by Sinuisan** [supsm/MCPPPP#21]
Attempted to convert 'A Little Taste of Jerm', with only Fabric Sky Box ticked (as this is the issue I'm having with Magnesium and this texture pack). 

Conversion finishes but fails to find a few files. Log attached. 

Upon loading resource pack MC fails to load the pack.
[mcpppp-log.txt](https://github.com/TeamDeusVult/CustomSkyboxes/files/7901574/mcpppp-log.txt)

### Steps - 
Custom Sky Boxes JAR placed in mods folder
Downloaded Windows version of MCPPP from github
Ran MCPPP -windows and pointed at resource pack. 
Un-ticked VMT and CIM
Ran. 

Truthfully it may be user error, I found the wiki a little confusing. 

### **Important stuff**
MC 1.16.6
Forge 36.2.20
Magnesium 1.5
 

**Resourcepack**
[](https://www.curseforge.com/minecraft/texture-packs/a-little-taste-of-jerm?__cf_chl_captcha_tk__=3spgFFAx7Ll_Tmzn5H0Mwi.DgFLGL23nMKDBPD7BJxo-1642643289-
[mcpppp-log.txt](https://github.com/supsm/MCPPPP/files/7901654/mcpppp-log.txt)
0-gaNycGzNENE)
**Logs**

**Comment by supsm** [comment]
It isn't your issue, the pack referenced some files that didn't exist. If you look in `assets/minecraft/optifine/sky/world0/` you won't find `cloud2.png`, `sky_clouds1.png`, or any of the other files. I think it's an issue for the pack creator to fix, in the conversion process a transparent image is used as a placeholder so you don't get a black and purple skybox.

**Comment by Sinuisan** [comment]
So I had a prod at it, updated file names and re-ran MCPPP with no errors. 

MC still fails to load it. 
Pack does work normally, its only when I run it through MCPPPP that is fails. 

I've compared its file structure in the fabric sky boxes to Vices (for science) and its different. However I don't really understand how they're 'supposed' to look. 

Attached the version that MCPPPP produced. 
[A+Little+Taste+of+Jerm+V2.5-1.16.zip](https://github.com/supsm/MCPPPP/files/7915576/A%2BLittle%2BTaste%2Bof%2BJerm%2BV2.5-1.16.zip)

**Comment by supsm** [comment]
Oh I didn’t read carefully. The errors you can ignore and don’t need to be taken care of, however you need the fabricskyboxes mod which is only available for fabric. As for “it fails to load”, does it have no effect, or does it get deselected?

**Comment by Sinuisan** [comment]
MC loads it up and then promptly unloads it and the 'Resource pack failed' toast popup appears. 

Using Custom Sky Boxes [https://www.curseforge.com/minecraft/mc-mods/custom-skyboxes](url) which point to your program as a solution for converting packs from optifine to Fabric - which Magnesium (Forge port of Sodium) can read with CustomSkyBoxes. 


I've run a few other packs through MCPPPP and they work... but with mixed results. 
JohnSmith Legacy for example has a black frame around one of the images which is meant to be a sunrise, and its also at the wrong position relative to the sun/time of day. 

Having looked through it further I think its because these images are not supposed to have a North,S,E,W,Top,Bottom version- but they're being duplicated anyway? Also noticing the Jerm output has lots of transparent images, which I *think* is MCPPPP functioning correctly. 

Either way the more I look at what MCPPPP is doing the more impressed I am.

**Comment by supsm** [comment]
Huh… I’ll take a look at the skybox when I can, and there will also be a new release this weekend, if not later today

**Comment by Sinuisan** [comment]
Sweet, thanks for helping with this. I've been hitting it with a wrench and my wrench is looking tired. 
If you want any logs, files etc from my end shout.

**Comment by supsm** [comment]
Can you try 0.6.0? I changed a lot of things and couldn’t reproduce this issue when I tried. Let me know if it breaks again

**Comment by Sinuisan** [comment]
Dida basic test, still fails to load when applied in MC. 

Running same setup as earlier:

Grabbed a fresh download of Little Taste of Germ 
Ran through MCPPPP
Few 'unable to locate' 
Finished MCPPPP process. 

Loaded into MC with Magnesium and CustomSkyBoxes installed. 
Failed to load texture pack.

**Comment by supsm** [comment]
I see. One of the skies (the last one, sky27.properties) had to time specifier at all, which caused the program to be confused. I will probably release a version soon with some other minor fixes, but before then you may download the build artifacts from the [compile workflow](https://github.com/supsm/MCPPPP/actions/runs/1749310045).

**Comment by supsm** [comment]
Please let me know if the issue has been fixed in 0.6.1

**Comment by Sinuisan** [comment]
Ahoy! Sorry I've been a bit busy. 

Just ran it now, no longer 'fails to load' the pack (hooray!) 

But the sky box is still not quite right, with one or two issues. The big ones are stars layering over the moon, sunset effect in the wrong position and the skyboxes being possibly too bright? Stars/clouds are being washed out. 

Attached some images to clarify, and some examples on optifine to show the normal output (which looking at I forgot how majestic this skybox is)  

https://imgur.com/a/9MSAhDB

I'm not sure how far you want to take this - I'd understand if you'd consider this pack outside the normal use case as I'm aware its got more to it than most other skybox packs (or at least I've not seen other packs doing shooting stars etc). 

That said, I appreciate your efforts in this, and am keen to keep trying to get this to work.

**Comment by supsm** [comment]
Hmmm it's probably a combination of broken rotation, broken alpha, and unsupported blend modes.  
The only one I can fix would be the broken rotation, I will take a look sometime after I finish vmt conversion (4 days to a month)

**Comment by supsm** [comment]
All of these issues should be fixed in the latest release (will release in ~10 mins). Please let me know if the issue persists.

**Comment by Sinuisan** [comment]
Some progress, but still has issues for me. 

https://imgur.com/a/YP8hrzD


Posted some images to imgur to keep it tidy, but in short:

Looks like the saturation or 'backlight' is still overwhemling the textures. Shooting Stars might need to just be overlooked, edge case. Your call. 

Otherwise...everything is where its supposed to be I think. Awesome work 👍
