### ISSUE TITLE
game wont launch

### ISSUE THREAD

**Issue by CD64Real** [supsm/MCPPPP#25]
I put the mod in the mods for feather client.
The game crashes and nothing else. Is there anyway to fix this issue

**Comment by supsm** [comment]
I don't condone usage of feather client due to its shady and potentially illegal use of other mods. If you wish to receive actual support I recommend you first [install fabric yourself](https://fabricmc.net/wiki/player:tutorials:install). It's not as difficult as it may seem, it's only clicking a few buttons with MultiMC, GDlauncher, etc. All the mods from feather client should also be available standalone, but if there are any features you are missing, you can ask somewhere like [my discord server](https://discord.gg/waXJDswsaR) or #lounge in [CaffieneMC Discord](https://caffeinemc.net/discord)

**Comment by CD64Real** [comment]
Yeah well I like fps. Can I just run it once then play normally?

**Comment by supsm** [comment]
[Sodium](https://modrinth.com/mod/sodium) is the main optimization mod that feather client uses, it works just as well if not better on its own. I won't offer support for feather client since its practices are legally questionable.

**Comment by CD64Real** [comment]
The thing is I can care less. I just use it because its better for me

**Comment by supsm** [comment]
Sorry, Feather client uses most if not all of the mods without the owner's permission, and as I am involved in the community and want to support the creators and developers of the mods, I won't help you. If you really insist on continuing to use feather client, you're on your own.

**Comment by hellosway** [comment]
If feather client includes sodium, then it must have a way to replace sodium with your own library, and to freely distribute the library. It must also make all modifications to the library/mod (sodium) available and freely redistribution under the lgpl or gpl. Because you cannot do any of this, feather is a major lgpl violation. It is piracy to use feather client.

**Comment by supsm** [comment]
Same with lithium and starlight, which also seem to be pre-installed

**Comment by hellosway** [comment]
> Same with lithium and starlight, which also seem to be pre-installed

Because it is commercial, if it ends up making a lot of money then it seems like a very good idea to file a gpl violation against it. But a lawyer has to spend their time and money on it.

**Comment by thegu5** [comment]
> If feather client includes sodium, then it must have a way to replace sodium with your own library, and to freely distribute the library. It must also make all modifications to the library/mod (sodium) available and freely redistribution under the lgpl or gpl. Because you cannot do any of this, feather is a major lgpl violation. It is piracy to use feather client.

They work around it by swapping the automatic download button with one that opens both a folder and the official download site for the mod.

Pretty painful

**Comment by Zetvue** [comment]
lol

**Comment by desktopdotini** [comment]
lol

**Comment by supsm** [comment]
Sus

**Comment by RNGesusIsAdopted** [comment]
L

**Comment by Feel65** [comment]
oh my god Jesus Christ

`null intelligence`

**Comment by Feel65** [comment]
and remember kids,

#
![6A49937E-37AE-475F-A932-B7C8DDECBD04](https://user-images.githubusercontent.com/69548576/168419073-7da34463-b753-496d-8ba7-b66a7042915f.jpeg)

**Comment by Feel65** [comment]
<h1>
Is batch even a language
</h1>

<h2> 
Or is it whatever fucking shit Microsoft decides to name their command line or whatever
</h2>

<h3>
like seriously fr
</h3>

what do you think 
<input type=“text” id=“bad” name=“bad/>

**Comment by supsm** [comment]
Please don't insult others regardless of what they use or play. This is also a very serious discussion, please refrain from going off-topic. But to answer the question, Batch is a programming language somewhat similar to Bash or Powershell (all 3 are recognized by github). It is also actually turing complete, as someone wrote a [brainf interpreter in batch](https://github.com/yyny/Brainfuck-In-Batch).

**Comment by CD64Real** [comment]
> and remember kids,
> 
> ![6A49937E-37AE-475F-A932-B7C8DDECBD04](https://user-images.githubusercontent.com/69548576/168419073-7da34463-b753-496d-8ba7-b66a7042915f.jpeg)

Why the fuck are you going deep into my account this shit is going too far
Like I just was talking about feather and mcppppp thing or whatever
It just went to far. I'm being attacked by everybody for no reason.
Like chill down dudes

**Comment by Zetvue** [comment]
Holy shit what the fuck

**Comment by supsm** [comment]
Can everyone just calm down, it's not even that serious and personal attacks shouldn't be involved regardless. I was only trying to help this user transition away from feather client due to their sketchy practices. We shouldn't attack anyone either way.
