### ISSUE TITLE
Feature Request: Which version supports versions prior to c++20

### ISSUE THREAD

**Issue by NoWait126** [supsm/MCPPPP#29]
I want to build from source code, I found `Prerequisites: Git, Cmake, compiler with c++20` in `Readme`, but I should use c++14,
so, is there a  version supports c++14?

**Comment by supsm** [comment]
No, your compiler needs to support c++20. Is there a specific reason why you are unable to use it?

**Comment by NoWait126** [comment]
thanks, some of my codes use old version of c++, I will upgrade them.

**Comment by supsm** [comment]
Alright! Obviously I would prefer if my code was as compatible as possible, but C++17 filesystem stuff is absolutely crucial for a project like this, and I was a bit too drawn in by C++20 to let it pass :P  
Hopefully I don't adopt C++23 before anyone supports it yet....
