### ISSUE TITLE
I need your help 

### ISSUE THREAD

**Issue by Juank081** [supsm/MCPPPP#5]
Hello, I am a user of a java minecraft server with mods but it has a peculiarity ... it has crossplay with bedrock and with this comes a problem, the resource pack, normally it would be passed with a normal converter, but it needs optifine to work and it would be Your program helps a lot but I don't have a pc, I need you to help me doing the process to remove the optifine with your program and be able to transfer it with a resource pack converter if you want to help me talk to the discord of 
juank081#9927

**Comment by supsm** [comment]
My converter does not work with bedrock, since there are no mods which can accept the formats

**Comment by Rajbir98** [comment]
lol dumb question
