### ISSUE TITLE
Release MCPPPP in CurseForge Like You Released In Modrinth

### ISSUE THREAD

**Issue by Rajbir98** [supsm/MCPPPP#6]

**Comment by moehreag** [comment]
https://discord.com/channels/824116179534348288/864355026855657472/868321028999360542

**Comment by Rajbir98** [comment]
Ok I Seen The Poll When It Will Be Released I Will Close This Issue Or This Issue Get Marked As Not To Be Fixed And Closed By supsm

**Comment by Rajbir98** [comment]
I think i Should Close This Issue Byeeeeeeeeeeeeee
