### ISSUE TITLE
Feature Request: Make the build instructions easier to follow.

### ISSUE THREAD

**Issue by OsoaGitHub** [supsm/MCPPPP#8]
**Describe the solution you'd like**
I would like the build instructions to be easier to follow for people like me who don't know C++

**Describe alternatives you've considered**
When the instructions say something like `Add fltk.lib as a library`, it would be nice if it specified on which file, where and exactly what to type.

**Comment by supsm** [comment]
If you don't know C++, you probably shouldn't be building from source. There are precompiled binaries that you can use, they will be more stable as well.  
On another note, I've specified exactly what file (fltk.lib). Options vary from compiler to compiler, and most IDEs will have some text field where libraries can be specified.

**Comment by OsoaGitHub** [comment]
I’m only trying to build from source so I can get a version that supports Chime. Could you give me a build of that please?

**Comment by OsoaGitHub** [comment]
Nvm I’ve just seen the latest release

**Comment by supsm** [comment]
Chime isn't fully supported, and I haven't made any changes since at least 0.4.0 lol
